---

all:
  hosts:
    apache:
      ansible_host: 3.90.213.74
      ansible_port: 22
      ansible_user: ec2-user
      ansible_connection: ssh
      ansible_ssh_private_key_file: /Users/sesterhg/code/amazonCode/sap-account.pem
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o ControlMaster=auto -o ControlPersist=60s"