---

- name: Create sample file
  file:
    path: "{{ sample_file_full_path }}"
    state: touch

- name: Change sample file contents
  lineinfile:
    path: "{{ sample_file_full_path }}"
    line: "This is sample file created by Ansible"
    insertafter: EOF